name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Options: 'adopt', 'zulu', 'temurin', etc.
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn test --file login-maven/pom.xml

      - name: Run tests
        run: mvn test --file login-maven/pom.xml

      - name: Archive test reports
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: login-maven/target/surefire-reports/

